wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    code_path: code/aerial_gym/rl_training/cleanrl/ppo_continuous_action.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.12
    start_time: 1717744172
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 35
      4: 3.7.12
      5: 0.12.21
      8:
      - 5
anneal_lr:
  desc: null
  value: false
batch_size:
  desc: null
  value: 8192
checkpoint:
  desc: null
  value: null
clip_coef:
  desc: null
  value: 0.2
clip_vloss:
  desc: null
  value: false
compute_device_id:
  desc: null
  value: 0
ent_coef:
  desc: null
  value: 0.0
experiment_name:
  desc: null
  value: ppo_continuous_action
flex:
  desc: null
  value: false
gae_lambda:
  desc: null
  value: 0.95
gamma:
  desc: null
  value: 0.99
graphics_device_id:
  desc: null
  value: 0
headless:
  desc: null
  value: false
horovod:
  desc: null
  value: false
learning_rate:
  desc: null
  value: 0.0026
max_grad_norm:
  desc: null
  value: 1
minibatch_size:
  desc: null
  value: 4096
norm_adv:
  desc: null
  value: true
norm_adv_off:
  desc: null
  value: false
num_envs:
  desc: null
  value: 512
num_minibatches:
  desc: null
  value: 2
num_steps:
  desc: null
  value: 16
num_threads:
  desc: null
  value: 0
physics_engine:
  desc: null
  value: SimType.SIM_PHYSX
physx:
  desc: null
  value: false
pipeline:
  desc: null
  value: gpu
play:
  desc: null
  value: false
rl_device:
  desc: null
  value: cuda:0
seed:
  desc: null
  value: 1
sim_device:
  desc: null
  value: cuda:0
sim_device_id:
  desc: null
  value: 0
sim_device_type:
  desc: null
  value: cuda
slices:
  desc: null
  value: 0
subscenes:
  desc: null
  value: 0
target_kl:
  desc: null
  value: null
task:
  desc: null
  value: quad
torch_deterministic:
  desc: null
  value: true
torch_deterministic_off:
  desc: null
  value: false
total_timesteps:
  desc: null
  value: 30000000
track:
  desc: null
  value: true
update_epochs:
  desc: null
  value: 4
use_gpu:
  desc: null
  value: true
use_gpu_pipeline:
  desc: null
  value: true
vf_coef:
  desc: null
  value: 2
wandb_entity:
  desc: null
  value: mayank1507
wandb_project_name:
  desc: null
  value: demo
